### ISSUE TITLE
add button to print posts / export by pdf + make those look nice

### ISSUE THREAD

**Issue by JosephMcArthur** [sparcopen/infrastructure#37]

**Comment by JosephMcArthur** [comment]
Any way we can hide:

* next / previous post
* related

and maybe add a downloaded from statement so people can get back easily?

I think we may also, in at least some cases, want to pre-generate a download link for these. Perhaps we could add some custom yaml and include a download link? Then the button can use an if statement to grab that?

**Comment by JosephMcArthur** [comment]
The download link could be used to put this on reports too of course.

**Comment by JosephMcArthur** [comment]
I think taking the summary out may be good too. When on top of the post in many cases it can end up being a bit weird.

**Comment by ssssoz** [comment]
Removed & pushed: 
- next/previous
- related
- summary
- print button
- extra margins on header & footer

**Comment by ssssoz** [comment]
TODO: 
- [x] make sure that overflown text doesn’t get cut off between pages
- [x] figure out why asterisk fleurons are not displayed in print
- [x] adjust horizontal padding on footer
- [x] replace mention of "Content on this site is licensed..." to something more appropriate in print

**Comment by JosephMcArthur** [comment]
>  replace mention of "Content on this site is licensed..." to something more appropriate in print

We can probably just change this on the site to be:

Content is licensed under a Creative Commons Attribution 4.0 International license.

which should make it nicer on the site and fix the page...

**Comment by ssssoz** [comment]
@JosephMcArthur and also that bit about adding a mention of the website’s URL

**Comment by ssssoz** [comment]
Added a "Downloaded from.." statement for print only (and added a `.print-only` class)

**Comment by JosephMcArthur** [comment]
- [x] change button link / text depending on front matter
- [x] prominant download link for reports on report pages (link specified in font matter)
- [x] remove a few more bits (including code licence)

**Comment by ssssoz** [comment]
- [x] Join box isn’t hidden for some reason
- [x] Same with download button
