### ISSUE TITLE
copy for 'get updates' section

### ISSUE THREAD

**Issue by JosephMcArthur** [sparcopen/infrastructure#42]
# Get new and sensitive analysis in your inbox

Get the latest analyses, and ones too sensitive to post, sent to you and your team's inbox by joining SPARC.

[Join SPARC](https://sparcopen.org/become-a-member/) | [Follow on Twitter](http://twitter.com/sparc_na)

**Comment by ssssoz** [comment]
Done in 0bd3870fc5af30997564064656f0d844eb4bcc46 -- can you look at it? We can make it prettier later.

**Comment by JosephMcArthur** [comment]
prefect, I think this is great to get in ahead of feedback.
