### ISSUE TITLE
Visually emphasise top (latest?) post on threads

### ISSUE THREAD

**Issue by ssssoz** [sparcopen/infrastructure#44]

**Comment by ssssoz** [comment]
@JosephMcArthur 

Something like this? 

<img width="1440" alt="Screenshot 2020-06-17 at 14 18 08" src="https://user-images.githubusercontent.com/6668406/84902986-67747800-b0a5-11ea-961f-153a9ff836fe.png">

Should I do the same for topic threads as well?

**Comment by JosephMcArthur** [comment]
I think something like this is certainly worth a shot.

And yes, lets have it for topics, everything really.

Joseph McArthur
Assistant Director: Right to Research Coalition ( http://righttoresearch.org )
Director / Founder: Open Access Button ( http://openaccessbutton.org )
Twitter: @Mcarthur_Joe ( https://twitter.com/Mcarthur_Joe )
Skype: joseph_mcarthur

**Comment by ssssoz** [comment]
Which one do you prefer & what elements do you like/dislike?

# Option 1 

Bold option with red colour block. 

<img width="1440" alt="Screenshot 2020-06-17 at 15 59 50" src="https://user-images.githubusercontent.com/6668406/84914630-b7f2d200-b0b3-11ea-8e27-77b5d98cb403.png">

---

# Option 2

Conservative & echoing the "About us" infobox in the post pages. 

<img width="1440" alt="Screenshot 2020-06-17 at 16 00 24" src="https://user-images.githubusercontent.com/6668406/84914861-056f3f00-b0b4-11ea-86d1-78013fa7478a.png">
