### ISSUE TITLE
Clarify purpose of bookmark icon

### ISSUE THREAD

**Issue by ssssoz** [sparcopen/infrastructure#45]

**Comment by ssssoz** [comment]
Simple HOME text on hover / focus / active 

![4867842539ba2bf0d9bd250ce2591f63](https://user-images.githubusercontent.com/6668406/85610340-d4ac7e00-b64e-11ea-8f8e-7ac48c6beca9.gif)

**Comment by JosephMcArthur** [comment]
perfect
