### ISSUE TITLE
make authors section on pages

### ISSUE THREAD

**Issue by JosephMcArthur** [sparcopen/infrastructure#47]

**Comment by ssssoz** [comment]
Done in 2d62c31c9ed9a9b9aa563ffc3a1052e2ab081a58

**Comment by JosephMcArthur** [comment]
do we still want this on report / the homepage

**Comment by ssssoz** [comment]
As discussed, I’m worried that displaying the "About" block on every page might have a banner blindness effect. Only displaying it on single posts / articles emphasises the sense of authorship that we’re trying to convey. 

Should we close it for now?
