### ISSUE TITLE
font flash on load

### ISSUE THREAD

**Issue by JosephMcArthur** [sparcopen/infrastructure#48]
When doing a hard refresh you can see some fonts load and get used before our proper ones, and it causes a bit of a flash. 

We may not care, but I want to flag as usually I don't see this.

**Comment by ssssoz** [comment]
The dreaded FOUT. It should only happen when we clear the cache. I haven’t seen it on the site before though.

**Comment by JosephMcArthur** [comment]
Any chance you know how to fix it? If not, I may ask for a hand from cottage labs.

**Comment by ssssoz** [comment]
The default Google Fonts way doesn't do that usually

**Comment by ssssoz** [comment]
Can’t reproduce this issue, even with hard refresh...

**Comment by JosephMcArthur** [comment]
ah, I may have made a partial fix! 

The flash I see now is on pages like this https://infrastructure.sparcopen.org/risk-mitigation on "risk mitigation" and "contents".

What are the weights there. Are those included in the initial request to fonts?

**Comment by JosephMcArthur** [comment]
Hmm I can see they are. 

I'm going to make this won't fix, it's extremely minor.
