### ISSUE TITLE
make template viewable on the site but not turn up in next / previous posts

### ISSUE THREAD

**Issue by JosephMcArthur** [sparcopen/infrastructure#51]

**Comment by JosephMcArthur** [comment]
unpublish or hide when it ships

**Comment by ssssoz** [comment]
@JosephMcArthur I moved the template to a `_drafts/` directory. It shouldn’t be published in `_site/`. If you ever need to see the drafts, you just need to run `jekyll s --drafts`. Can you make sure that it is now removed from threads? 

Done in 4c3d50a294a90cff903e2537477a8b176ea6f94c

**Comment by JosephMcArthur** [comment]
That fixes it for now, which is really all I care about at this point, but it's less than ideal to need to do this.

- [X] BUT, we can also use the solution I discussed about having this live on dev, but not on production.

Joseph McArthur
Assistant Director: Right to Research Coalition ( http://righttoresearch.org )
Director / Founder: Open Access Button ( http://openaccessbutton.org )
Twitter: @Mcarthur_Joe ( https://twitter.com/Mcarthur_Joe )
Skype: joseph_mcarthur
