### ISSUE TITLE
have template be the starting point for all posts

### ISSUE THREAD

**Issue by JosephMcArthur** [sparcopen/infrastructure#53]
it needs all catagories, some editing instructions, etc

**Comment by JosephMcArthur** [comment]
- [x] have this make clear that bold isn't good and neither is h1 in posts

**Comment by JosephMcArthur** [comment]
maybe use github templates

**Comment by JosephMcArthur** [comment]
@sssoz can you take a look at the template as is and make sure it looks good to you.

**Comment by ssssoz** [comment]
Didn’t have time to look at this before -- sorry -- looks good though.
