### ISSUE TITLE
Add "Copied" tooltip to copy-to-clipboard feature

### ISSUE THREAD

**Issue by ssssoz** [sparcopen/infrastructure#55]

**Comment by ssssoz** [comment]
Need custom JS for this

**Comment by JosephMcArthur** [comment]
ah, no worries for now then

Joseph McArthur
Assistant Director: Right to Research Coalition ( http://righttoresearch.org )
Director / Founder: Open Access Button ( http://openaccessbutton.org )
Twitter: @Mcarthur_Joe ( https://twitter.com/Mcarthur_Joe )
Skype: joseph_mcarthur
