### ISSUE TITLE
Clean up footer -- too many elements 

### ISSUE THREAD

**Issue by ssssoz** [sparcopen/infrastructure#56]

**Comment by ssssoz** [comment]
Just to make sure, this only applies to post pages, yes? With the About + Subscribe infoboxes.

**Comment by JosephMcArthur** [comment]
Yup, I think so.

Joseph McArthur
Assistant Director: Right to Research Coalition ( http://righttoresearch.org )
Director / Founder: Open Access Button ( http://openaccessbutton.org )
Twitter: @Mcarthur_Joe ( https://twitter.com/Mcarthur_Joe )
Skype: joseph_mcarthur

**Comment by ssssoz** [comment]
Should we close?
