### ISSUE TITLE
how to display date on posts and in threads

### ISSUE THREAD

**Issue by JosephMcArthur** [sparcopen/infrastructure#59]

**Comment by ssssoz** [comment]
Just making sure -- do you want the date on every type of post, including the reports? Or only in TOPICS and LATEST threads?

**Comment by JosephMcArthur** [comment]
just topic and latest threads plz, I think!

Joseph McArthur
Assistant Director: Right to Research Coalition ( http://righttoresearch.org )
Director / Founder: Open Access Button ( http://openaccessbutton.org )
Twitter: @Mcarthur_Joe ( https://twitter.com/Mcarthur_Joe )
Skype: joseph_mcarthur

**Comment by JosephMcArthur** [comment]
ah, two seconds. 

On pages that don't have reports, I think we should put date where currently it just says 'the report'. 

e.g https://infrastructure.sparcopen.org/dutch-consortia-elsevier-contract

**Comment by JosephMcArthur** [comment]
and on report pages: https://infrastructure.sparcopen.org/landscape-analysis, it probably makes senses to put the date in the sidebar once... 

If we need to add dates to front matter for that of course happy to do that!

**Comment by ssssoz** [comment]
> ah, two seconds.
> 
> On pages that don't have reports, I think we should put date where currently it just says 'the report'.
> 
> e.g https://infrastructure.sparcopen.org/dutch-consortia-elsevier-contract

I hadn’t noticed that. Done and pushed.

**Comment by ssssoz** [comment]
> and on report pages: https://infrastructure.sparcopen.org/landscape-analysis, it probably makes senses to put the date in the sidebar once...

We do need to add the date in each report’s frontmatter

**Comment by ssssoz** [comment]
...make sure it’s ISO 8601 format

**Comment by JosephMcArthur** [comment]
> We do need to add the date in each report’s frontmatter

done. used same format as all other dates.
