### ISSUE TITLE
increase font size on cover... if it looks good

### ISSUE THREAD

**Issue by JosephMcArthur** [sparcopen/infrastructure#60]
Joe thinks about 10% is good. e.g if you just zoom in a touch.

**Comment by ssssoz** [comment]
@JosephMcArthur two quick options:

# 1:  Increasing base font size by 10% (22px)

![screencapture-127-0-0-1-4000-2020-06-17-17_46_02 (1)](https://user-images.githubusercontent.com/6668406/84934143-d3b7a180-b0ce-11ea-940f-45394b66b7f2.png)

# 2: Decreasing cover content width 

![screencapture-127-0-0-1-4000-2020-06-17-19_14_07](https://user-images.githubusercontent.com/6668406/84934114-cac6d000-b0ce-11ea-84db-68d67ae4f2dc.png)

In both cases, I could also increase the leading / `line-height`.

**Comment by JosephMcArthur** [comment]
1 :)

Joseph McArthur
Assistant Director: Right to Research Coalition ( http://righttoresearch.org )
Director / Founder: Open Access Button ( http://openaccessbutton.org )
Twitter: @Mcarthur_Joe ( https://twitter.com/Mcarthur_Joe )
Skype: joseph_mcarthur
