### ISSUE TITLE
are we **really** happy with the homepage?

### ISSUE THREAD

**Issue by JosephMcArthur** [sparcopen/infrastructure#61]
¯\_(ツ)_/¯

**Comment by ssssoz** [comment]
**Time estimate: 1.5 days?** *

I also have some ideas -- it would be a completely different way to present the contents though (i.e. not in a table like it is now).

\* @JosephMcArthur Who else needs to approve this page?

**Comment by JosephMcArthur** [comment]
I'd ask for feedback from our team, but I think could approve it myself after that. Understood it would be completely different, and that might make sense.

Joseph McArthur
Assistant Director: Right to Research Coalition ( http://righttoresearch.org )
Director / Founder: Open Access Button ( http://openaccessbutton.org )
Twitter: @Mcarthur_Joe ( https://twitter.com/Mcarthur_Joe )
Skype: joseph_mcarthur

**Comment by JosephMcArthur** [comment]
Mock-ups: https://www.figma.com/proto/m45GZHBnUOZMdpQWTJrGL5/SPARC-Infra?node-id=357%3A483&scaling=min-zoom

Curious, how close does this come to a homepage that you love?

**Comment by ssssoz** [comment]
I think it makes a much better use of horizontal space on this page (again the weird "funnel" that we get with the current homepage really bothers me). I feel maybe 50% closer to what I think would be the ideal homepage :). A lot of work needed on type sizes & margins. Visuals, even abstract ones, would really help I think.

**Comment by JosephMcArthur** [comment]
Next step here is spend an hour co-working to condense (or plan to condense) what we've done into a shareable good-enough version. No rush, just lmk when works for you: https://doodle.com/mm/josephmcarthur/book

**Comment by JosephMcArthur** [comment]
okay, we have a great mock up! Will set up new issue for build.
