### ISSUE TITLE
how to post members only content

### ISSUE THREAD

**Issue by JosephMcArthur** [sparcopen/infrastructure#62]
For this we'll need:

- [x] an element that makes it super obvious not to share, 
- [x] make sure it doesn't come up in normal threads / latest, 
- [x] don't allow indexing / robots
- [x] make a member-only thread

**Comment by ssssoz** [comment]
Netlify allows password-protected pages, but you need to pay for that -- $45/month. 

This would be "private" HTML pages and, like you mentioned during our call, it wouldn’t be any different from sharing PDFs to members (they can still share it if they want even if they’re not "supposed" to).

**Time estimate:  1 day**
- Designing the alert box that indicates this is member-only
- Implementing the HTML page based on the public post template

**Comment by ssssoz** [comment]
> * [x]  don't allow indexing / robots

I’ve added the noindex metatag and a robots.txt file, but you should also do it in the Google Search Console.

**Comment by ssssoz** [comment]
All members-only content is in `_members/`. I’ve included one example post.

It will be accessible through https://infrastructure.sparcopen.org/members/ (once on `master`)

**Comment by JosephMcArthur** [comment]
- [x] write some copy
- [x] configure google search console
- [x] get some content

**Comment by ssssoz** [comment]
Sorry this closed with the merge to master

**Comment by JosephMcArthur** [comment]
it doesn't appear that google search console can do anything about this, noindex is enough.

**Comment by JosephMcArthur** [comment]
I've just had the stupidest thought. This repository is public, meaning the code and content is public. 

To actually do this privately we'd need to fork the repo, make a private version, and point netfly and a subdomain at it. At first glance this isn't all that much work so I'm not worried... but glade I noticed now and not in a week.

**Comment by ssssoz** [comment]
Hah! I hadn’t even thought about this. 

Are you hoping to have members-only content soon?

**Comment by JosephMcArthur** [comment]
Yes. We have a backlog that can be uploaded.

**Comment by JosephMcArthur** [comment]
- [x] We should turn off the cite it functionality here I think. 
- [x] maybe remove open license too
