### ISSUE TITLE
add contact page or place to ask questions

### ISSUE THREAD

**Issue by JosephMcArthur** [sparcopen/infrastructure#72]
Noted in feedback people may want this

**Comment by JosephMcArthur** [comment]
this can be as part of the authors box. 

About us | contact us

**Comment by ssssoz** [comment]
Examples of "About this contributor" sections on article footers: 

<img width="643" alt="Screenshot 2020-06-18 at 14 42 40" src="https://user-images.githubusercontent.com/6668406/85027594-01a1f200-b172-11ea-9bf1-ef015e6f1b31.png">

---

<img width="612" alt="Screenshot 2020-06-18 at 14 41 21" src="https://user-images.githubusercontent.com/6668406/85027604-036bb580-b172-11ea-95e1-3b490ec69dd2.png">

---

<img width="379" alt="Screenshot 2020-06-18 at 14 40 52" src="https://user-images.githubusercontent.com/6668406/85027606-049ce280-b172-11ea-8b3c-8ed365e0883b.png">

---

<img width="694" alt="Screenshot 2020-06-18 at 14 40 17" src="https://user-images.githubusercontent.com/6668406/85027608-049ce280-b172-11ea-8580-dfc4aa117467.png">

**Comment by ssssoz** [comment]
Authors’ box, for a post with this frontmatter:

```
---
authors:
  - nicole
  - joe
---
```

<img width="1197" alt="Screenshot 2020-06-24 at 18 22 58" src="https://user-images.githubusercontent.com/6668406/85602933-c5760200-b647-11ea-99b8-59e4b2e6c976.png">

--- 

Authors’ box, when no authors have been specified / default info: 

<img width="1421" alt="Screenshot 2020-06-24 at 18 28 05" src="https://user-images.githubusercontent.com/6668406/85603626-741a4280-b648-11ea-8fa0-991eab57e781.png">

SPARC’s _Contact form_ link leads to: https://sparcopen.org/contact/

**Comment by ssssoz** [comment]
Use case for a single author, frontmatter looks like this: 

```
---
authors: joe
---
```

<img width="803" alt="Screenshot 2020-06-24 at 18 56 24" src="https://user-images.githubusercontent.com/6668406/85607849-6961ac80-b64c-11ea-8153-27e2537efef9.png">
