### ISSUE TITLE
put footnotes in a smaller font

### ISSUE THREAD

**Issue by JosephMcArthur** [sparcopen/infrastructure#79]

**Comment by JosephMcArthur** [comment]
generally, the problem is it's not obvious they're footnotes. other ideas suggested include using italics, a footnote header, etc

**Comment by ssssoz** [comment]
You can use the variable `$typescale-06` for smaller type

**Comment by JosephMcArthur** [comment]
Can you give me a code snippet to put in posts, or, ideally, can you set up the style sheet to do this automatically?

**Comment by ssssoz** [comment]
The stylesheet is already set up with all of these variables; I can do it now though :) 

I have to see how to config the footnotes in kramdown so that we may add a header ("Footnotes") as well.

**Comment by JosephMcArthur** [comment]
thanks. Smaller font may be more than enough to show they're footnotes, but if not, then whatever else you think makes sense is grand too

Joseph McArthur
Assistant Director: Right to Research Coalition ( http://righttoresearch.org )
Director / Founder: Open Access Button ( http://openaccessbutton.org )
Twitter: @Mcarthur_Joe ( https://twitter.com/Mcarthur_Joe )
Skype: joseph_mcarthur

**Comment by ssssoz** [comment]
Can’t find anything in the [docs](https://jekyllrb.com/docs/configuration/markdown/) about adding a custom "Footnotes" header. Closing with the smaller type, might be just enough like you said.
