### ISSUE TITLE
use full width images in posts

### ISSUE THREAD

**Issue by JosephMcArthur** [sparcopen/infrastructure#80]
https://infrastructure.sparcopen.org/landscape-analysis/elsevier

**Comment by ssssoz** [comment]
Do you want people to be able to click on the images, or for the images to appear, inline, in full-size? It will bleed & overlap with the right-side content, unless we make the right-side content not sticky.

**Comment by JosephMcArthur** [comment]
erm, I want them the full width of the text (so, the RHS column would be clear)

**Comment by ssssoz** [comment]
Ah okay, then it’s not a CSS issue. Do you just need to crop the images then?

**Comment by JosephMcArthur** [comment]
Oh… is there just a bunch of whitespace in the images 🙃?

Joseph McArthur
Assistant Director: Right to Research Coalition ( http://righttoresearch.org )
Director / Founder: Open Access Button ( http://openaccessbutton.org )
Twitter: @Mcarthur_Joe ( https://twitter.com/Mcarthur_Joe )
Skype: joseph_mcarthur

**Comment by ssssoz** [comment]
Yep!

**Comment by JosephMcArthur** [comment]
Ah, if it's fast for you to crop them then that would be great... but if it isn't let me know and I deal with it.

**Comment by ssssoz** [comment]
Sure, but shouldn’t you have the source material instead of the PNGs? Probably easier to export from there -- if not, no problem, I can do that too...

**Comment by JosephMcArthur** [comment]
Should do, let me hunt down.

Joseph McArthur
Assistant Director: Right to Research Coalition ( http://righttoresearch.org )
Director / Founder: Open Access Button ( http://openaccessbutton.org )
Twitter: @Mcarthur_Joe ( https://twitter.com/Mcarthur_Joe )
Skype: joseph_mcarthur

**Comment by JosephMcArthur** [comment]
I've cropped them
