### ISSUE TITLE
The pull out sentance overlaps the links on the right side on Mac - not a ton - but a bit.

### ISSUE THREAD

**Issue by JosephMcArthur** [sparcopen/infrastructure#81]
https://infrastructure.sparcopen.org/landscape-analysis/teaching-and-student-activities#the-events-of-2016-were-startling-at-the-end-of-2015-pearson%E2%80%99s-m

**Comment by ssssoz** [comment]
Had to remove the negative margin, so it doesn’t necessarily "pull over" to the side but still looks like a pull-quote. It was too complicated to play with z-indices; adding a background to the pull-quote  made it impossible to click on the sidebar elements.

**Comment by ssssoz** [comment]
<img width="1111" alt="Screenshot 2020-06-22 at 18 23 15" src="https://user-images.githubusercontent.com/6668406/85316904-726c4580-b4b5-11ea-8840-70fcaa791347.png">
