### ISSUE TITLE
pagination doesn't respect linkout posts

### ISSUE THREAD

**Issue by JosephMcArthur** [sparcopen/infrastructure#95]
e.g go back here: https://test.infrastructure.sparcopen.org/dutch-consortia-elsevier-contract

**Comment by ssssoz** [comment]
See https://github.com/sparcopen/infrastructure/commit/a04cfd9e52bad007d9ab51f8d9e09516c45e610f 

It works now, but it also means that users won’t be able to skip past linkout posts -- from https://test.infrastructure.sparcopen.org/dutch-consortia-elsevier-contract they will click the previous article which opens in a new tab (the Science article) but they can’t consult the post before that one.

**Comment by JosephMcArthur** [comment]
Yeah, I suppose that's just a downside we'll need to live with. I think that's better than landing on an empty post.

Joseph McArthur
Assistant Director: Right to Research Coalition ( http://righttoresearch.org )
Director / Founder: Open Access Button ( http://openaccessbutton.org )
Twitter: @Mcarthur_Joe ( https://twitter.com/Mcarthur_Joe )
Skype: joseph_mcarthur
